"""
formatter.py — Utilities to format the LLM structured output for display.
"""

from .schemas import Answer

# Mandatory legal disclaimer for all generated answers
DISCLAIMER = (
    "> **LEGAL DISCLAIMER:** This answer was generated by an AI assistant based "
    "on provided regulatory documents. It does not constitute legal, financial, "
    "or professional advice. Always consult with qualified legal counsel or the "
    "relevant regulator (e.g., CBUAE, VARA) before making compliance decisions."
)


def format_answer_markdown(answer: Answer) -> str:
    """
    Formats the structured Answer object into a clean Markdown string.
    Appends citations and the mandatory legal disclaimer.
    """
    
    # 1. Start with the final text from the LLM
    md = f"{answer.final_text}\n\n"
    
    # 2. Add System Metadata (Mode and Confidence)
    md += "---\n"
    md += f"**Analysis Mode:** {answer.answer_mode} | **Confidence:** {answer.confidence_score * 100:.1f}%\n\n"
    
    # 3. Add Citations if present
    if answer.citations and answer.answer_mode != "Refuse":
        md += "### 📚 Verified Citations\n"
        for i, cit in enumerate(answer.citations, 1):
            # Format: 1. [doc_id prefix...] "exact quote" - Explanation
            short_id = cit.chunk_id.split('_')[0] if '_' in cit.chunk_id else cit.chunk_id[:8]
            md += f"{i}. **[{short_id}]** *\"{cit.exact_quote}\"* — {cit.explanation}\n"
        md += "\n"
        
    # 4. Mandatory Legal Disclaimer
    md += "---\n"
    md += DISCLAIMER
    
    return md
