"""
schemas.py — Pydantic models for structured LLM outputs.
"""

from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Represents a direct quote-span citation from a regulatory chunk."""
    chunk_id: str = Field(..., description="The chunk_id of the source document.")
    exact_quote: str = Field(..., description="An EXACT substring extracted from the chunk text. Must match character-for-character.")
    explanation: str = Field(..., description="Brief explanation of how this quote answers the user's query.")


class Answer(BaseModel):
    """The structured answer output generated by the LLM."""
    answer_mode: Literal["Extract", "Summarize", "Compare", "Refuse"] = Field(
        ..., 
        description="The mode of the answer based on the guardrails."
    )
    confidence_score: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Confidence score from 0.0 to 1.0 that the answer is accurate and fully supported by the citations."
    )
    citations: List[Citation] = Field(
        default_factory=list, 
        description="List of exact quote citations. Must be empty if answer_mode is 'Refuse'."
    )
    final_text: str = Field(
        ..., 
        description="The final Markdown-formatted answer. If refusing, state the reason clearly."
    )
    # Server-side fields (not populated by the LLM — set by our pipeline)
    retrieval_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Server-computed retrieval confidence from cross-encoder scores. Not set by LLM."
    )
    composite_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weighted composite: 0.4*retrieval + 0.3*citation_rate + 0.3*llm_conf. Not set by LLM."
    )
